version: '3.8'

services:
  kareer-blue:
    image: ${ECR_REGISTRY}/kareer-server:${IMAGE_TAG}
    container_name: kareer-blue
    ports:
      - "8080:8082"
    environment:
      - TZ=Asia/Seoul
      - "JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS:--Xms512m -Xmx2048m}"
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    env_file:
      - .env
    networks:
      - kareer-net
    depends_on:
      - redis
    restart: always

  kareer-green:
    image: ${ECR_REGISTRY}/kareer-server:${IMAGE_TAG}
    container_name: kareer-green
    ports:
      - "8081:8082"
    environment:
      - TZ=Asia/Seoul
      - "JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS:--Xms512m -Xmx2048m}"
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    env_file:
      - .env
    networks:
      - kareer-net
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: kareer-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - kareer-net
    restart: always

networks:
  kareer-net:
    driver: bridge

volumes:
  redis-data:
