name: cd-main

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'deployment/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      # 1. ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - name: ğŸ”„ Code Checkout
        uses: actions/checkout@v4

      # 2. ë°°í¬ íŒŒì¼ ë³µì‚¬
      - name: ğŸ“„ Copy deployment files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "deployment/*"
          target: "/home/ubuntu/app"

      # 3. ë°°í¬ ìŠ¤í¬ë¦½íŠ¸ ì‹¤í–‰
      - name: ğŸ”† Execute blue-green deploy script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app/deployment
            export IMAGE_TAG=${{ github.sha }}
            chmod +x deploy.sh
            ./deploy.sh
